# Generated by Django 3.1.7 on 2021-07-05 07:34

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=api.models.random_key, max_length=10, unique=True)),
                ('quote', models.CharField(max_length=500, unique=True)),
                ('contain_adult_lang', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='role', to='api.role')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='show', to='api.show')),
            ],
        ),
    ]
