# Generated by Django 3.1.7 on 2021-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='contain_adult_lang',
            field=models.BooleanField(default=False, verbose_name='Contain adult language'),
        ),
    ]
