# Generated by Django 3.1.7 on 2021-07-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='ips',
            new_name='visitors',
        ),
    ]
