# Generated by Django 3.1.7 on 2021-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_auto_20210708_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
